### ISSUE TITLE
Failure when mixing null and string values in ODBC

### ISSUE THREAD

**Issue by jhoekx** [timeseer-ai/kukur#178]
When string values and null values are in the same column, Kukur fails with:

```
2023-08-29 13:33:43,012 ERROR timeseer.background_jobs.worker background_worker_0 : Expected bytes, got a 'float' object
Traceback (most recent call last):
  File "timeseer\background_jobs\worker.py", line 527, in run
  File "timeseer\blocks\analysis\univariate_job.py", line 175, in run
  File "timeseer\blocks\analysis\univariate_job.py", line 199, in _analyze
  File "timeseer\blocks\analysis\univariate_job.py", line 248, in _get_input
  File "timeseer\blocks\block_input.py", line 445, in get_data
  File "timeseer\blocks\block_input.py", line 480, in get_table
  File "timeseer\blocks\block_input.py", line 249, in _fetch_new_data
  File "C:\hostedtoolcache\windows\Python\3.11.4\x64\Lib\functools.py", line 946, in _method
  File "timeseer\source\app.py", line 240, in _get_data_id
  File "C:\hostedtoolcache\windows\Python\3.11.4\x64\Lib\functools.py", line 946, in _method
  File "timeseer\source\app.py", line 253, in _get_data_selector
  File "venv\Lib\site-packages\kukur\source\__init__.py", line 215, in get_data
  File "venv\Lib\site-packages\kukur\source\__init__.py", line 216, in <listcomp>
  File "venv\Lib\site-packages\kukur\source\__init__.py", line 274, in _get_data_chunk
  File "venv\Lib\site-packages\kukur\source\__init__.py", line 99, in _retry
  File "venv\Lib\site-packages\kukur\source\__init__.py", line 95, in _retry
  File "venv\Lib\site-packages\kukur\source\sql.py", line 230, in get_data
  File "pyarrow\table.pxi", line 3849, in pyarrow.lib.Table.from_pydict
  File "pyarrow\table.pxi", line 5401, in pyarrow.lib._from_pydict
  File "pyarrow\array.pxi", line 357, in pyarrow.lib.asarray
  File "pyarrow\array.pxi", line 327, in pyarrow.lib.array
  File "pyarrow\array.pxi", line 39, in pyarrow.lib._sequence_to_array
  File "pyarrow\error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow\error.pxi", line 123, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: Expected bytes, got a 'float' object
```

**Comment by smeganck** [comment]
Wait for install at Borealis

**Comment by smeganck** [comment]
Install @Borealis happened @AdriaanVHB @sebastienverhelst ??

**Comment by sebastienverhelst** [comment]
install happened - running the flows again and Noel will inform us about the issue

cc @AdriaanVHB

**Comment by smeganck** [comment]
@sebastienverhelst  any update?

**Comment by sebastienverhelst** [comment]
Analysis successful

From: smeganck ***@***.***>
Date: Wednesday, 27 September 2023 at 14:01
To: timeseer-ai/kukur ***@***.***>
Cc: Sébastien Verhelst ***@***.***>, Mention ***@***.***>
Subject: Re: [timeseer-ai/kukur] Failure when mixing null and string values in ODBC (Issue #178)

@sebastienverhelst<https://github.com/sebastienverhelst> any update?
